### ISSUE TITLE
allowed_authentication_types not updated properly for install_shibboleth: true

### ISSUE THREAD

**Issue by mirjan-hoffmann** [TIBHannover/edu-sharing-box#43]
The shihbboleth configuration adjustment to homeApplication.properties.xml (https://github.com/TIBHannover/edu-sharing-box/blob/master/ansible/roles/edu-sharing/tasks/common/shibboleth_after.yml) is not working. The adjustment is overwritten and rolled back.

I needed to process the adjustment manually (via UI -> admin-area) to make it work.

It should work automatically by the ansible-scripts.

We should try to fix the file adjustment. If we cannot find a way, another option would be to use the webservice PUT `/edu-sharing/rest/admin/v1/applications/homeApplication.properties.xml` (json)

**Comment by mirjan-hoffmann** [comment]
@Edmondi-Kacaj How did you configure this on the internal Test-System? Also manually?

**Comment by Edmondi-Kacaj** [comment]
hello @mirjan-hoffmann 

Yes **shibboleth_after.yml** just add a key 

```xml
<entry key="allowed_authentication_types">shibboleth</entry>

```

and in the docker version, we don't need this, is added automatically by script inside the container, 

in the .env file, you can find the variable below, and if this REPOSITORY_SERVICE_AUTH_EXTERNAL is true then it will add this property itself in `homeApplication.properties.xml`
```sh
# --- authentication service
REPOSITORY_SERVICE_AUTH=shibboleth
# --- use external authentication service
REPOSITORY_SERVICE_AUTH_EXTERNAL=true
```

So we don't need this, or we can use it, and comment the REPOSITORY_SERVICE_AUTH_EXTERNAL=true, so both of them works

**Comment by mirjan-hoffmann** [comment]
@Edmondi-Kacaj Ok, then this is not a general problem of the adjustment of homeApplication.properties.xml - I'll rename the issue.

But the problem is still there. It is not working. If I set `install_shibboleth: true`, then `<entry key="allowed_authentication_types">shibboleth</entry>` is missing in homeApplication.properties.xml - this should be set automatically if shibboleth is activated (whichever way is used to configure this in edu-sharing v8)

**Comment by Edmondi-Kacaj** [comment]
Hello @mirjan-hoffmann 

I created a pull request for this problem, can you have a look
